### ISSUE TITLE
[Epic] Firebase 연동

### ISSUE THREAD

**Issue by dev-riverkim** [Couch-Coders/7th-park-fe#11]
- [x] Firebase 개발자 계정 등록
- [x] Firebase  앱 생성
- [x] Firebase Package 설치 및 세팅
- [x] Google Provider 로 로그인 및 jwt 얻기
- [x] Context 이용하여 Auth 상태 주입하기
