### ISSUE TITLE
[Epic] 검색, 필터링 기능

### ISSUE THREAD

**Issue by dev-riverkim** [Couch-Coders/7th-park-fe#4]
- [ ] 검색 기능 어떻게 구현할 지 생각
- [ ] 지역별 필터링 구현
- [ ] 별점순, 거리순 리스트 정렬 구현
