### ISSUE TITLE
[Epic] 메인페이지 레이아웃

### ISSUE THREAD

**Issue by dev-riverkim** [Couch-Coders/7th-park-fe#7]
- [x] 검색 및 필터 마크업
- [x] 슬라이드 영역 마크업
- [x] 카드 리스트 마크업
- [x] 헤더 영역 마크업 및 컴포넌트 분리
- [x] 푸터 영역 마크업 및 컴포넌트 분리
